import type {Metadata} from "next";
import {Barriecito} from "next/font/google";
import "./globals.sass";
import ModulesProvider from '@/provider/ModulesProvider'

const barriecito = Barriecito({
  variable: "--font-barriecito",
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body className={barriecito.variable}>
      <ModulesProvider>
        {children}
      </ModulesProvider>
    </body>
    </html>
  );
}